# Generated by Django 6.0.8 on 2026-08-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_app', models.DateField(auto_now_add=True, verbose_name="Date d'approvisionnement")),
                ('quantite_produit', models.PositiveIntegerField(default=0, verbose_name='Quantité totale de produits')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'ordering': ['-date_app'],
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du catalogue')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProduitMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.catalogue', verbose_name='Catalogue')),
            ],
            options={
                'verbose_name': 'Produit médical',
                'verbose_name_plural': 'Produits médicaux',
                'ordering': ['nom'],
                'unique_together': {('catalogue', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='DetailsApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix unitaire d'achat")),
                ('montant', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Montant')),
                ('date_peremption', models.DateField(verbose_name='Date de péremption')),
                ('numero_lot', models.CharField(max_length=50, verbose_name='Numéro de lot')),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='catalogue.approvisionnement', verbose_name='Approvisionnement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_approvisionnement', to='catalogue.produitmedical', verbose_name='Produit médical')),
            ],
            options={
                'verbose_name': "Détail d'approvisionnement",
                'verbose_name_plural': "Détails d'approvisionnement",
                'ordering': ['-date_peremption'],
            },
        ),
    ]
