# Generated by Django 5.0.7 on 2026-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitmedical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit'),
        ),
    ]
