# Generated by Django 5.0.7 on 2026-08-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Identifiant unique du paramètre (ex: adresse_entreprise, taux_tva)', max_length=100, unique=True, verbose_name='Nom du paramètre')),
                ('valeur', models.TextField(help_text='Valeur du paramètre (texte, JSON, etc.)', verbose_name='Valeur')),
                ('description', models.TextField(blank=True, help_text='Description du rôle de ce paramètre', verbose_name='Description')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('type_rapport', models.CharField(choices=[('Ventes', 'Rapport des ventes'), ('Stock', 'Rapport de stock'), ('Approvisionnements', 'Rapport des approvisionnements'), ('Paiements', 'Rapport des paiements'), ('Factures', 'Rapport des factures'), ('Clients', 'Rapport des clients')], max_length=30, verbose_name='Type de rapport')),
                ('chemin_acces', models.FileField(blank=True, help_text='Fichier PDF/Excel généré', null=True, upload_to='rapports/%Y/%m/%d/', verbose_name="Chemin d'accès")),
                ('periode_debut', models.DateField(blank=True, help_text='Date de début de la période couverte par le rapport', null=True, verbose_name='Début de période')),
                ('periode_fin', models.DateField(blank=True, help_text='Date de fin de la période couverte par le rapport', null=True, verbose_name='Fin de période')),
                ('commentaires', models.TextField(blank=True, help_text='Notes ou observations sur le rapport', verbose_name='Commentaires')),
                ('genere_par', models.ForeignKey(limit_choices_to={'role': 'Administrateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_genres', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_generation'],
            },
        ),
    ]
