# Generated by Django 5.0.7 on 2026-08-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_panier_lignepanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('Especes', 'Espèces'), ('Carte', 'Carte bancaire'), ('MobileMoney', 'Mobile Money'), ('Cheque', 'Chèque')], default='Especes', max_length=20, verbose_name='Mode de paiement choisi par le client'),
        ),
    ]
